/**
 * Deep Research Types - GPT Researcher pattern implementation
 *
 * Based on Carnegie Mellon's #1 ranked research architecture:
 * Planner → Executor → Publisher
 */

/**
 * Research question generated by the Planner agent
 */
export interface ResearchQuestion {
  id: string;
  question: string;
  priority: 'high' | 'medium' | 'low';
  expectedScope: string;
}

/**
 * Research finding from an Executor agent
 */
export interface ResearchFinding {
  questionId: string;
  question: string;
  answer: string;
  sources: Source[];
  confidence: number; // 0-1
  timestamp: Date;
  tokensUsed: number;
}

/**
 * Source/citation from grounded search
 */
export interface Source {
  url?: string;
  title: string;
  snippet: string;
  relevanceScore?: number;
}

/**
 * Final research report from Publisher agent
 */
export interface ResearchReport {
  query: string;
  summary: string;
  findings: ResearchFinding[];
  synthesis: string;
  sources: Source[];
  metadata: ResearchMetadata;
}

/**
 * Metadata about the research process
 */
export interface ResearchMetadata {
  questionsGenerated: number;
  sourcesConsulted: number;
  totalTokensUsed: number;
  duration: number; // milliseconds
  model: string;
  timestamp: Date;
}

/**
 * Configuration for research orchestrator
 */
export interface ResearchConfig {
  maxQuestions?: number; // default: 5
  parallelExecutors?: number; // default: 3
  useGrounding?: boolean; // default: true
  thinkingLevel?: 'high' | 'medium' | 'low'; // default: high
  temperature?: number; // default: 1.0
  maxOutputTokens?: number; // default: 8192
  timeout?: number; // milliseconds, default: 1800000 (30 min)
}

/**
 * Progress update during research (for streaming)
 */
export interface ResearchProgress {
  stage: 'planning' | 'executing' | 'publishing' | 'finalizing' | 'complete';
  message: string;
  progress: number; // 0-100
  currentQuestion?: string;
  findings?: Partial<ResearchFinding>[];
}
